name: emuaio
description: "EmuAIO"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  clipboard: ^3.0.14
  flutter_downloader: ^1.12.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  http: ^1.6.0
  file_picker: ^10.3.8
  archive: ^4.0.7
  webview_flutter: ^4.13.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/icon/bureau/
    - assets/icon/train/