name: emuaio
description: ""
version: 3.0.0+3000

publish_to: 'none'

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  http: ^1.6.0
  file_picker: ^10.3.10
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/icon/bureau/
    - assets/icon/train/